config/routes.rb
Rails.application.routes.draw do

root :to => 'users#homepage'
 get 'users/tasawwuf', as: 'tasawwuf',:path => "tasawwuf"
 get 'users/about', as:'about', path: 'about'
 get 'users/bayanaat',as: 'bayanaat', path: 'bayanaat'
 get 'users/contact', as:'contact', path: 'contact'
 post 'users/create'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!
  
  # def index
  #   @users = User.all
  # end
 
  def homepage
    render layout: "home" 
  end

  def tasawwuf
  end

  def about
  end

  def bayanaat
  end

  def contact   
  @user = User.new
  end

  # def show    
  #   # @user = User.find(params[:id])
  # end

  # def new
  #   # @user = User.new
  # end

  def create  
    @user = User.new(user_params)     
    respond_to do |format|
    if @user.save

      # Sends email to user when user is created.
      ExampleMailer.sample_email(@user).deliver

      format.html { redirect_to root_path, notice: 'User was successfully created.' }
      format.json { render :show, status: :created, location: @user }
    else
      format.html { render :new }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
  end

  def update
  end

  # def edit
  # end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit!
    # params.require(:user).permit(:email, :first_name, :last_name, {avatars: []})
  end

  # def profile
  #   binding.pry
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hazratapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="">
	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>    
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'custom', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'custom' %>
    <%= csrf_meta_tags %>


    <title>Modern Business - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
   <!--  <link href="css/bootstrap.css" rel="stylesheet"> -->

    <!-- Add custom CSS here -->
    <!-- <link href="custom.css" rel="stylesheet"> -->
 <!--    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet"> -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>
  <body>
  <%= yield %>
  </body>
</html>

app/views/users/about.html.erb
Hazrat Maulana Mufti Khursheed Anwar (db)
Shaykh Zulfiqar Ahmad is one of leading shaykhs of Tasawwuf in the present era. Formally granted authorization (ijazah) in the Naqshbandi spiritual path (tariqah), he retired from his position as an electrical engineer at the age of forty to devote himself entirely to the service of Islam. He regularly travels to more than thirty countries transforming the lives of people all over the world. A testament to his deep love for Allah, his uncompromising dedication to sunnah of the blessed Prophet, and his firm adherence to Islamic Law (shariah) is that thousands of religious scholars and students of Islamic learning are among his students (murids). Shaykh Zulfiqar Ahmad regularly delivers lectures in both English and Urdu across the world. Furthermore, he has written dozens of books many of which have been translated into several languages. Online versions of both talks and writings are available.

Mufti Khursheed Anwar’s spiritual chain traces back through a series of authentic teachers all the way to the Holy Prophet. To view a listing of the masters of this silsilah (chain), click on the link below.

The Silsilah of Mufti Khursheed Anwar(db) – Trace the chain of the honorable Mashaikh Naqshband from Mufti Khursheed Anwar back to our beloved Prophet.

 

app/views/users/bayanaat.html.erb
coming soon.

app/views/users/contact.html.erb
Mufti Khusrheed Anwar Naqshbandi(db)
Khalifa Majaz Shaykh Zulfiqar Ahmad (db)


<div>
  <%= form_for :user , url:  users_create_path do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name%><br>
    <%= f.radio_button :is_female, 'male', :checked=> true%> 
    <%= label :is_female_no, 'Male' %>
    <%= f.radio_button :is_female, 'female' %>
    <%= label :is_female_yes, 'Female' %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city, autofocus: true %>
  </div>  
   <div class="field"> <div class="field"> 
  
    <%= f.label :state %><br />
    <%= f.text_field :state, autofocus: true %>
  </div>
   
    <div class="field">
    <%= f.label :country%><br />
    <%= f.select :country, collection: CountryStateSelect.countries_collection %>   
  </div> 


 
   
  <div class="field">
    <%= f.label :email%>
    <%= f.text_field :email%><br>
    </div>
    <div class="field">
    <%= f.label :subject%>
    <%= f.text_field :subject%><br>
    </div>
    <div class="field">
    <%= f.label :message%>
    <%= f.text_area :message %><br>
    </div>
    <%= f.submit'Submit'%>
  <%end%>

</div>

app/views/users/homepage.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                <a class="navbar-brand" href="index.html">Modern Business</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%=link_to 'HOME',root_path%>
                    </li>
                    <li><%= link_to 'TASAWWUF', tasawwuf_path %>
                    <li><%= link_to 'HAZRAT MUFTI KURSHEED ANWAR(db)',about_path%>
                    <li><%= link_to 'BAYANAAT', bayanaat_path %>
                    </li>
                    <li><%= link_to 'Contact', contact_path %>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                            <li><a href="portfolio-item.html">Single Portfolio Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li><a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li><a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="full-width.html">Full Width Page</a>
                            </li>
                            <li><a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li><a href="faq.html">FAQ</a>
                            </li>
                            <li><a href="404.html">404</a>
                            </li>
                            <li><a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('/assets/hazrat9.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Modern Business - A Bootstrap 3 Template</h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/hazrat8.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Ready to Style & Add Content</h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/carousal-image-1.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a>
                    </h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/carousal-image-2.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a>
                    </h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/carousal-image-3.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a>
                    </h1>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('/assets/carousal-image-4.jpg');"></div>
                <div class="carousel-caption">
                    <h1>Additional Layout Options at <a href="http://startbootstrap.com">http://startbootstrap.com</a>
                    </h1>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </div>

    <div class="section">

        <div class="container">

            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <h3><i class="fa fa-check-circle"></i> Bootstrap 3 Built</h3>
                    <p>The 'Modern Business' website template by <a href="http://startbootstrap.com">Start Bootstrap</a> is built with <a href="http://getbootstrap.com">Bootstrap 3</a>. Make sure you're up to date with latest Bootstrap documentation!</p>
                </div>
                <div class="col-lg-4 col-md-4">
                    <h3><i class="fa fa-pencil"></i> Ready to Style & Edit</h3>
                    <p>You're ready to go with this pre-built page structure, now all you need to do is add your own custom stylings! You can see some free themes over at <a href="http://bootswatch.com">Bootswatch</a>, or come up with your own using <a href="http://getbootstrap.com/customize/">the Bootstrap customizer</a>!</p>
                </div>
                <div class="col-lg-4 col-md-4">
                    <h3><i class="fa fa-folder-open"></i> Many Page Options</h3>
                    <p>This template features many common pages that you might see on a business website. Pages include: about, contact, portfolio variations, blog, pricing, FAQ, 404, services, and general multi-purpose pages.</p>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section -->

    <div class="section-colored text-center">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <h2>Modern Business: A Clean & Simple Full Website Template by Start Bootstrap</h2>
                    <p>A complete website design featuring various single page templates from Start Bootstraps library of free HTML starter templates.</p>
                    <hr>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section-colored -->

    <div class="section">

        <div class="container">

            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Display Some Work on the Home Page Portfolio</h2>
                    <hr>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="portfolio-item.html">
                        <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="portfolio-item.html">
                        <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="portfolio-item.html">
                        <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="portfolio-item.html">
                        <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="portfolio-item.html">
                        <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6">
                    <a href="portfolio-item.html">
                        <img class="img-responsive img-home-portfolio" src="http://placehold.it/700x450">
                    </a>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section -->

    <div class="section-colored">

        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <h2>Modern Business Features Include:</h2>
                    <ul>
                        <li>Bootstrap 3 Framework</li>
                        <li>Mobile Responsive Design</li>
                        <li>Predefined File Paths</li>
                        <li>Working PHP Contact Page</li>
                        <li>Minimal Custom CSS Styles</li>
                        <li>Unstyled: Add Your Own Style and Content!</li>
                        <li>Font-Awesome fonts come pre-installed!</li>
                        <li>100% <strong>Free</strong> to Use</li>
                        <li>Open Source: Use for any project, private or commercial!</li>
                    </ul>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <img class="img-responsive" src="http://placehold.it/700x450/ffffff/cccccc">
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section-colored -->

    <div class="section">

        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <img class="img-responsive" src="http://placehold.it/700x450">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <h2>Modern Business Features Include:</h2>
                    <ul>
                        <li>Bootstrap 3 Framework</li>
                        <li>Mobile Responsive Design</li>
                        <li>Predefined File Paths</li>
                        <li>Working PHP Contact Page</li>
                        <li>Minimal Custom CSS Styles</li>
                        <li>Unstyled: Add Your Own Style and Content!</li>
                        <li>Font-Awesome fonts come pre-installed!</li>
                        <li>100% <strong>Free</strong> to Use</li>
                        <li>Open Source: Use for any project, private or commercial!</li>
                    </ul>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.section -->

    <div class="container">

        <div class="row well">
            <div class="col-lg-8 col-md-8">
                <h4>'Modern Business' is a ready-to-use, Bootstrap 3 updated, multi-purpose HTML theme!</h4>
                <p>For more templates and more page options that you can integrate into this website template, visit Start Bootstrap!</p>
            </div>
            <div class="col-lg-4 col-md-4">
                <a class="btn btn-lg btn-primary pull-right" href="http://startbootstrap.com">See More Templates!</a>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright © Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <!-- JavaScript -->
    
    <script src="custom.js"></script>

app/views/users/tasawwuf.html.erb
What Is Tasawwuf ?
Tasawwuf is a branch of Islamic knowledge which focuses on the spiritual development of the Muslim.

Allah  sent His final messenger, Prophet Muhammad , as a source of knowledge for the entire ummah. He was the fountain of Quran, Hadith, tafsir, rhetoric, fiqh, and so on. After the Prophet, the scholars of this ummah carried and propagated each of these branches of knowledge. Because no one person can attain the perfection of the Prophet , who single handedly assumed all of these roles, various branches of the Islamic sciences developed. For example, Imam Abu Hanifah preserved the science of fiqh and after him thousands of scholars continued in his footsteps. Hence these scholars preserved the fiqh of the Prophet . Similarly Imam Bukhari and the other famous scholars of Hadith, preserved the words of the Prophet. The scholars of tajweed preserved the recitation of the Prophet . And, the scholars of Arabic grammar preserved the language of the Prophet .

Along these lines, the Prophet  was the model of spirituality for the world. His God-consciousness, deep spirituality, acts of worship, and love for Allah  were preserved and propagated by an Islamic science called Tasawwuf. The aim of the scholars of this science was purification of the heart, and development of consciousness of Allah  through submission to the shariah and sunnah.

How is Tasawwuf Related to Sufism?
Studying the life of the Prophet , the scholars who propagated the science of tasawwuf understood that a requisite for approaching Allah  was abandonment of the common pursuits of the world. They often wore wool because of its simplicity and low cost. In Arabic the word for wool is suf and thus, those who wore it became known as the Sufis. Another possible derivation of the word comes from the root word safa, which means “to clean.” Because the scholars of tasawwuf focused on cleansing the heart, they later became known as the Sufis.

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>